### ISSUE TITLE
TypeError: list indices must be integers or slices, not dict

### ISSUE THREAD

**Issue by Tibladar** [Kismon/kismon#14]
Kismon shows only one AP regardless of filter settings when connected to a live Kismet server.
Kismets Web GUI works fine

**Log**:
```
INFO     [config.py:111] loading json config
DEBUG    [map.py:392] set source openstreetmap
INFO     [client_rest.py:71] Client: start http://[redacted]
INFO     [client_rest.py:190] authenticating...
INFO     [client_rest.py:202] authenticated
devices/last-time/-1566035196/devices.ekjson
INFO     [networks.py:110] Loading networks.json
INFO     [networks.py:131] Total networks 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kismon-1.0.0-py3.6.egg/kismon/core.py", line 327, in queues_handler_networks
    self.queue_handler_networks(server_id)
  File "/usr/local/lib/python3.6/dist-packages/kismon-1.0.0-py3.6.egg/kismon/core.py", line 301, in queue_handler_networks
    source = device['kismet.device.base.seenby'][sid]
TypeError: list indices must be integers or slices, not dict
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
devices/last-time/-2/devices.ekjson
```

**OS**: Linux Mint 19.2
**Kismet**: 2019-08-R1 via kismetwireless.net/repos/apt/
**Kismon**: git master clone (pulled 08/17/2019)
**Kismet Python module**: installed, GitHub master clone  (pulled 08/17/2019)

**Comment by Tibladar** [comment]
Changing `core.py` on line 301 from
`source = device['kismet.device.base.seenby'][sid]`
to
`source = sid`
seems to work

**Comment by dreadnought** [comment]
Thanks for reporting this issue, I applied the fix to master.
