### ISSUE TITLE
Kismon shows no wifi devices

### ISSUE THREAD

**Issue by BaumGuard** [Kismon/kismon#18]
Hello,
I've installed Kismon from the AUR and put my USB wifi adapter into monitor mode:
`sudo airmon-ng start wlan1`
Then I've started Kismon and set **URI**, **Username** and **Password**. There seem to be no error messages after hitting **Connect**.
However, there are now no wifi devices appearing in the **Network** section. Also it says **Devices: 0**.
Is it because GPS isn't enabled (which my notebook doesn't support) and if yes, can I also somehow run Kismon without GPS?

**Kismet version:** 2022-08-R1
**Kismon version:** 1.0.1

Thank you for your help in advance!

**Comment by dreadnought** [comment]
Hi,
the AUR package was outdated, so I've updated the it to the latest Kismon version (1.0.3) now. Please download the file again and retry.

https://aur.archlinux.org/packages/kismon

**Comment by BaumGuard** [comment]
I have updated Kismon now but it still doesn't work. There are again no wifi devices shown. I have also copied `kismet_httpd.conf` from `/root/.kismet` to `~/.kismet` and to `~/config/.kismet` but that doesn't seem to help.

**Comment by dreadnought** [comment]
Normally you don't need to copy any config files or set monitor mode manually these days. What happens when you open Kismets Web UI in the browser (`http://127.0.0.1:2501`) and enter the password that was written to `~/.kismet/kismet_httpd.conf`? Does it show you your adapter in the Data Sources section?

**Comment by BaumGuard** [comment]
The wifi adapter is shown as `wlan0mon` in the section `Data Sources`.

**Comment by BaumGuard** [comment]
I have now installed Kismon on Arch Linux but I encounter the same problem again. When I start Kismon from the command line, I also get an error message:

```
21:22:04,556 INFO     [config.py:111] loading json config
21:22:04,565 DEBUG    [map.py:392] set source openstreetmap
21:22:04,600 INFO     [client_rest.py:71] Client: start http://localhost:2501
21:22:04,608 INFO     [client_rest.py:190] authenticating...
21:22:04,622 INFO     [client_rest.py:202] authenticated
devices/last-time/-1670790125/devices.ekjson
21:22:04,688 INFO     [networks.py:110] Loading networks.json
21:22:04,689 INFO     [networks.py:131] Total networks 0
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/kismon/core.py", line 287, in queues_handler
    self.queue_handler(server_id)
  File "/usr/lib/python3.10/site-packages/kismon/core.py", line 205, in queue_handler
    if data['kismet.common.location.fix'] == 0 or data['kismet.common.location.geopoint'] == [0, 0]:
KeyError: 'kismet.common.location.fix'
devices/last-time/-2/devices.ekjson

```
Kismon seems to connect to Kismet but doesn't show any network devices.

**Comment by pinoverclock** [comment]
Add this function before the build function to the PKGBUILD:

`prepare() {`
`  cd "${srcdir}/${pkgname}-${pkgver}/${pkgname}"`
`  sed -i "s/            if data\['kismet.common.location.fix'\] == 0 or data\['kismet.common.location.geopoint'\] == \[0, 0\]:/            if data\['kismet.common.location.geopoint'\] == \[0, 0\]:/" core.py`
`  for file in core.py networks.py; do`
`    sed -i "s/'kismet.common.seenby.last_time'/'kismet_common_seenby.last_time'/g;`
`        s/'kismet.common.seenby.num_packets'/'kismet_common_seenby_num_packets'/g;`
`        s/'kismet.common.seenby.signal'/'kismet_common.seenby_signal'/g;`
`        s/'kismet.common.signal.type'/'kismet_common_signal_type'/g;`
`        s/'kismet.common.seenby.uuid'/'kismet_common_seenby_uuid'/g;`
`        s/'kismet.common.signal.last_signal'/'kismet_common_signal_last_signal'/g;`
`        s/'kismet.device.base.macaddr'/'kismet_device_base_macaddr'/g;`
`        s/'kismet.device.base.seenby'/'kismet_device_base_seenby'/g;`
`        s/'kismet.common.signal.last_signal'/'kismet_common_signal_last_signal'/g;`
`        s/'kismet.common.signal.max_signal'/'kismet_common_signal_max_signal'/g;`
`        s/'kismet.common.signal.min_signal'/'kismet_common_signal_min_signal'/g;`
`        s/'kismet.common.signal.type'/'kismet_common_signal_type'/g;`
`        s/'kismet.device.base.channel'/'kismet_device_base_channel'/g;`
`        s/'kismet.device.base.crypt'/'kismet_device_base_crypt'/g;`
`        s/'kismet.device.base.first_time'/'kismet_device_base_first_time'/g;`
`        s/'kismet.device.base.last_time'/'kismet_device_base_last_time'/g;`
`        s/'kismet.device.base.location'/'kismet_device_base_location'/g;`
`        s/'kismet.device.base.macaddr'/'kismet_device_base_macaddr'/g;`
`        s/'kismet.device.base.manuf'/'kismet_device_base_manuf'/g;`
`        s/'dot11.device.advertised_ssid_map'/'dot11_device_advertised_ssid_map'/g;`
`        s/'dot11.device'/'dot11_device'/g;`
`        s/'dot11.advertisedssid.ssid'/'dot11_advertisedssid_ssid'/g;`
`        s/'dot11.advertisedssid.crypt_set'/'dot11_advertisedssid_crypt_set'/g;`
`        s/'dot11.device.last_beaconed_ssid'/'dot11_device_last_beaconed_ssid'/g;`
`        s/'dot11.device.last_beaconed_ssid'/'dot11_device_last_beaconed_ssid'/g;`
`        s/'dot11.device.typeset'/'dot11_device_typeset'/g" $file`
`    done`
`}`

And recreate the package, that should make it work
